// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HicomInterview.Domain.Entities;

/// <summary>
/// Entity representing the database table or view
/// </summary>
public partial class Widget
{
    [Key]
    public int WidgetId { get; set; }

    [Timestamp]
    public byte[] RowVersion { get; set; }

    [StringLength(255)]
    public string FirstName { get; set; }

    [StringLength(255)]
    public string LastName { get; set; }

    [StringLength(255)]
    public string EmailAddress { get; set; }

    [Column("SKU")]
    [StringLength(50)]
    public string Sku { get; set; }

    public int? OldAddressId { get; set; }

    public int? NewAddressId { get; set; }

    [ForeignKey("NewAddressId")]
    [InverseProperty("WidgetNewAddress")]
    public virtual Address NewAddress { get; set; }

    [ForeignKey("OldAddressId")]
    [InverseProperty("WidgetOldAddress")]
    public virtual Address OldAddress { get; set; }
}
